### ISSUE TITLE
openmm.OpenMMException: Called setParameter() with invalid parameter name: bm_b0

### ISSUE THREAD

**Issue by samuelmurail** [Psivant/femto#24]
Hello,

I am trying to run a REST2 simulation to fold/unfold small peptide (chignolin and TrpCage).
It seems that `femto` is more adequate to study protein ligand system, but it looks anyway doable with `femto`.

Here is my code :

```python
from openmm import app
from openmm.app import PDBFile
from openmm import unit

import femto.md.config
import femto.md.constants
import femto.md.hremd
import femto.md.utils.openmm
import femto.md.rest
import femto.md.system

import parmed

pdb = PDBFile(f"tmp/test_explicit_equi.pdb")

forcefield_files = ['amber14-all.xml', 'amber14/tip3pfb.xml']
forcefield = app.ForceField(*forcefield_files)

system = forcefield.createSystem(
    pdb.topology,
    nonbondedMethod=app.PME,
    nonbondedCutoff=1.0 * unit.nanometers,
    constraints=app.HBonds,
    rigidWater=True,
    ewaldErrorTolerance=0.0005,
    hydrogenMass=3.0,
)

rest_temperatures = [300.0, 310.0, 320.0] * unit.kelvin
rest_betas = [
    1.0 / (unit.MOLAR_GAS_CONSTANT_R * rest_temperature)
    for rest_temperature in rest_temperatures
]

states = [
    {femto.md.rest.REST_CTX_PARAM: rest_beta / rest_betas[0]}
    for rest_beta in rest_betas
]

# REST requires both beta_m / beta_0 and sqrt(beta_m / beta_0) to be defined
# we can use a helper to compute the later from the former for each state
states = [
    femto.md.utils.openmm.evaluate_ctx_parameters(state, system)
    for state in states
]

# create the OpenMM simulation object
intergrator_config = femto.md.config.LangevinIntegrator(
    timestep=4.0 * unit.femtosecond,
)
integrator = femto.md.utils.openmm.create_integrator(
    intergrator_config, rest_temperatures[0]
)


structure = parmed.openmm.topsystem.load_topology(pdb.topology, system, pdb.positions)

femto.md.system.apply_hmr(system, structure)

solute_indices = [int(i.index) for i in pdb.topology.atoms() if i.residue.chain.id in ['A']]

rest_config = femto.md.config.REST(scale_torsions=True, scale_nonbonded=True)
femto.md.rest.apply_rest(system, solute_indices, rest_config)

print(states)

simulation = femto.md.utils.openmm.create_simulation(
    system,
    structure,
    None,  # or None to use the coordinates / box in structure
    integrator=integrator,
    state=states[0],
    platform=femto.md.constants.OpenMMPlatform.CUDA,
)


# define how the HREMD should be run
hremd_config = femto.md.config.HREMD(
    # the number of steps to run each replica for before starting to
    # propose swaps
    n_warmup_steps=150000,
    # the number of steps to run before proposing swaps
    n_steps_per_cycle=500,
    # the number of 'swaps' to propose - the total simulation length
    # will be n_warmup_steps + n_steps * n_cycles
    n_cycles=2000,
    # the frequency with which to store trajectories of each replica.
    # set to None to not store trajectories
    trajectory_interval=10  # store every 10 * 500 steps.
)
femto.md.hremd.run_hremd(
    simulation,
    states,
    hremd_config,
    # the directory to store sampled reduced potentials and trajectories to
    output_dir=pathlib.Path('test_hremd')
)
```

Here is the error:

```bash
[{'bm_b0': 1.0}, {'bm_b0': 0.967741935483871}, {'bm_b0': 0.9375}]
NaN detected for replica=0 state=0, retrying 1/5
NaN detected for replica=0 state=0, retrying 2/5
NaN detected for replica=0 state=0, retrying 3/5
NaN detected for replica=0 state=0, retrying 4/5
NaN detected for replica=0 state=0 that could not be resolved by retries.
Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
Traceback (most recent call last):
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/femto/md/utils/mpi.py", line 85, in get_mpi_comm
    yield comm
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/femto/md/hremd.py", line 640, in run_hremd
    _propagate_replicas(
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/femto/md/hremd.py", line 235, in _propagate_replicas
    simulation.step(n_steps)
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/openmm/app/simulation.py", line 212, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/openmm/openmm.py", line 9338, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
Traceback (most recent call last):
  File "/mnt/data_22/REST2_test/test_femto_2.py", line 92, in <module>
    femto.md.hremd.run_hremd(
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/femto/md/hremd.py", line 640, in run_hremd
    _propagate_replicas(
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/femto/md/hremd.py", line 235, in _propagate_replicas
    simulation.step(n_steps)
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/openmm/app/simulation.py", line 212, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/murail/miniforge3/envs/openmm/lib/python3.10/site-packages/openmm/openmm.py", line 9338, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
```

Is it something link to my installation of `femto` or am i doing something wrong ?

Cheers,
Samuel

**Comment by simon-boothroyd-genesis** [comment]
Hi Samuel, thanks for your question! 

It looks like you're trying to jump straight to running REST2 with a larger timestep without equilibration. If you try [minimizing and doing a small amount of gentler equilibration](https://psivant.github.io/femto/latest/guide-md/#running-md) does this help with the NaNs? (see also [`simulate_states`](https://psivant.github.io/femto/latest/reference/md/simulate/#femto.md.simulate.simulate_states) in addition to the single singular [`simulate_state`](https://psivant.github.io/femto/latest/reference/md/simulate/#femto.md.simulate.simulate_state), which can be used to seed the HREMD with equilibrated coords for each temperature)

**Comment by SimonBoothroyd** [comment]
Hi Samuel, thanks for your question!

It looks like you're trying to jump straight to running HREMD with a larger timestep without equilibration. If you try [minimizing and doing a small amount of gentler equilibration](https://psivant.github.io/femto/latest/guide-md/#running-md) does this help with the NaNs? (see also [simulate_states](https://psivant.github.io/femto/latest/reference/md/simulate/#femto.md.simulate.simulate_states) in addition to the single singular [simulate_state](https://psivant.github.io/femto/latest/reference/md/simulate/#femto.md.simulate.simulate_state), which can be used to seed the HREMD with equilibrated coords for each temperature)

**Comment by samuelmurail** [comment]
Hi Simon,

Thanks a lot for your feedback, that solve my issue !!

I have three more question:

1) I might need to run long REST2 simulation and I was wondering how can I activate the checkpoint save in the config in order to be able to restart simulation ?
2) Would that be possible to save in the log file, the different energy term Epp, Ewp and Eww (potential energy terms for solute-solute (scaled and not scaled), solute-solvent and solvent-solvent).
3) if I am using only REST2 from `femto` library, how should I cite `femto` ? Juste by citing the github deposit ?

Cheers,
Samuel

**Comment by samuelmurail** [comment]
Hi again,

I have solved the first question concerning checkpoints using `checkpoint_interval` option in `femto.md.config.HREMD()`.

However, I am still wondering how to extract the different energy terms, i have recomputed them from
the raw trajectory, but I'd like to check that some component are exact, i thought to compare them
to `u_kn`. But what exactly is the `u_kn` in `sample.arrow`. What is the reduced potentials ?

Cheers,
Samuel
