### ISSUE TITLE
An example of ATM not being able to run.

### ISSUE THREAD

**Issue by 9527567** [Psivant/femto#4]
I copied the ATM code from the tutorial, but unfortunately, an error occurred.
~~~python
import femto.fe.atm

config = femto.fe.atm.ATMConfig()
import pathlib

import femto.md.system

eralpha_dir = pathlib.Path("eralpha")

ligand_1, ligand_2 = femto.md.system.load_ligands(
    ligand_1_coords=eralpha_dir / "forcefield/2d/vacuum.mol2",
    ligand_1_params=eralpha_dir / "forcefield/2d/vacuum.parm7",
    ligand_2_coords=eralpha_dir / "forcefield/2e/vacuum.mol2",
    ligand_2_params=eralpha_dir / "forcefield/2e/vacuum.parm7",
)
receptor = femto.md.system.load_receptor(
    coord_path=eralpha_dir / "proteins/eralpha/protein.pdb",
    param_path=None,
    tleap_sources=config.setup.solvent.tleap_sources,
)
displacement = femto.fe.atm.select_displacement(
    receptor, ligand_1, ligand_2, config.setup.displacement
)
ligand_1_ref_query = ["@7", "@11", "@23"]  # OR None
ligand_2_ref_query = ["@12", "@7", "@21"]  # OR None
receptor_ref_query = ":36,39,40,42,43,77,80,81,84,95,97,111,113,114,117,118,214,215,217,218 & @CA"
  # OR None
complex_structure, complex_system = femto.fe.atm.setup_system(
    config,
    receptor,
    ligand_1,
    ligand_2,
    displacement,
    receptor_ref_query,
   ligand_1_ref_query,
   ligand_2_ref_query,
)

import femto.md.constants

coords = femto.fe.atm.equilibrate_states(
    complex_system,
    complex_structure,
    config.states,
    config.equilibrate,
    displacement,
    femto.md.constants.OpenMMPlatform.CUDA,
    reporter=None
)

import femto.md.reporting

output_dir = pathlib.Path("eralpha/outputs-atm")

reporter = femto.md.reporting.TensorboardReporter(output_dir)  # OR None
config.sample.analysis_interval = 10

femto.fe.atm.run_hremd(
    complex_system,
    complex_structure,
    coords,
    config.states,
    config.sample,
    displacement,
    femto.md.constants.OpenMMPlatform.CUDA,
    output_dir,
    reporter
)

~~~

~~~python
Traceback (most recent call last):
  File "/mnt/d/fep/femto/examples/test.py", line 28, in <module>
    complex_structure, complex_system = femto.fe.atm.setup_system(
  File "/home/z/mambaforge/lib/python3.10/site-packages/femto/fe/atm/_setup.py", line 248, in setup_system
    config.reference.ligand_method,
  File "/home/z/mambaforge/lib/python3.10/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ATMConfig' object has no attribute 'reference'
~~~~

**Comment by SimonBoothroyd** [comment]
Thanks for reporting this, and apologies for the delayed response. This is a typo in the docs I believe, and should be fixed by #9
